version: '3.8'
services:
  app:
    build: ./node-js app
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - redis
      - inference

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  inference:
    build: ./python-inference
    ports:
      - "5000:5000"
    env_file:
      - .env
