version: '3.8'
services:
  app:
    build: ./node-js app
    env_file:
      - .env
    ports:
      - "${APP_INTERNAL_PORT}:${APP_EXTERNAL_PORT}"
    depends_on:
      - redis
      - inference
    networks:
      - my-network
    volumes:
      - ./node-js/app:/app

  redis:
    image: redis:alpine
    env_file:
      - .env
    ports:
      - "${REDIS_INTERNAL_PORT}:${REDIS_EXTERNAL_PORT}"
    networks:
      - my-network

  inference:
    build: ./python-inference
    env_file:
      - .env
    ports:
      - "${PYTHON_INTERNAL_PORT}:${PYTHON_EXTERNAL_PORT}"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
