version: '3.8'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=Jawalter2020-
      - DB_NAME=Pa_DB_2024
      - JWT_SECRET=your_jwt_secret
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Jawalter2020- 
      MYSQL_DATABASE: Pa_DB_2024
      MYSQL_USER: root
      MYSQL_PASSWORD: Jawalter2020-
    ports:
      - '3306:3306'

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
